name: default

on:
  push:
    branches:
      - develop

jobs:
  bom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c bom.kibot.yaml
      uses: ./
      with:
        config: config/bom.kibot.yaml
        dir: output/
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: bom"
      run: |
        test -f output/docs/bom/*-bom.html && \
        test -f output/docs/bom/*-ibom.html && \
        test -f output/docs/bom/*-bom.xlsx
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c docs.kibot.yaml
      uses: ./
      with:
        config: config/docs.kibot.yaml
        dir: output/
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: schematic.svg"
      run: test -f output/docs/img/test-schematic.svg
    - name: "check output: schematic.pdf"
      run: test -f output/docs/test-schematic.pdf
    - name: "check output: test-mechanic.pdf"
      run: test -f output/docs/test-mechanic.pdf
    - name: "check output: test-documentation.pdf"
      run: test -f output/docs/test-documentation.pdf
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/

  gerbers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c gerbers.kibot.yaml 
      uses: ./
      with:
        config: config/gerbers.kibot.yaml
        dir: output/
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: gerber"
      run: |
        test -f output/gerbers/*B_CrtYd.gbr && \
        test -f output/gerbers/*F_CrtYd.gbr && \
        test -f output/gerbers/*B_Cu.gbr && \
        test -f output/gerbers/*F_Cu.gbr && \
        test -f output/gerbers/*B_Mask.gbr && \
        test -f output/gerbers/*F_Mask.gbr && \
        test -f output/gerbers/*B_Paste.gbr && \
        test -f output/gerbers/*F_Paste.gbr && \
        test -f output/gerbers/*B_SilkS.gbr && \
        test -f output/gerbers/*F_SilkS.gbr && \
        test -f output/gerbers/*B_CrtYd.gbr && \
        test -f output/gerbers/*F_CrtYd.gbr
    - name: "check output: gerber"
      run: |
        test -f output/gerbers/*-NPTH_drill.gbr && \
        test -f output/gerbers/*-NPTH_drill.drl && \
        test -f output/gerbers/*-PTH_drill.gbr && \
        test -f output/gerbers/*-PTH_drill.drl
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/

  plot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c plot.kibot.yaml
      uses: ./
      with:
        config: config/plot.kibot.yaml
        dir: output/
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: plot"
      run: |
        test -f output/docs/img/test-top.svg && \
        test -f output/docs/img/test-bottom.svg 
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/

  position:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c position.kibot.yaml
      uses: ./
      with:
        config: config/position.kibot.yaml
        dir: output/
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: position"
      run: |
        test -f output/gerbers/*pos*.csv
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/

  cad:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c model.kibot.yaml
      uses: ./
      with:
        config: config/model.kibot.yaml
        dir: output/
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: cad"
      run: |
        test -f output/cad/*.step
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/

  commit:
    runs-on: ubuntu-latest
    needs: [ cad, position, plot, gerbers, docs, bom ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/download-artifact@v2
      with:
        name: bom
        path: output/
    - uses: actions/download-artifact@v2
      with:
        name: cad
        path: output/
    - uses: actions/download-artifact@v2
      with:
        name: position
        path: output/
    - uses: actions/download-artifact@v2
      with:
        name: gerbers
        path: output/
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: output/
    - uses: actions/download-artifact@v2
      with:
        name: plot
        path: output/
    - uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        rebase: 'true'
        files: output/*
        name: kicad-export
        email: ci@github 
        commit-message: ${{ github.workflow }}
